name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm" # Enables pnpm caching automatically

      # Install dependencies with pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Run lint
      - name: Lint code
        run: pnpm lint

      # Run TypeScript type checking
      - name: Type check
        run: pnpm tsc --noEmit
